"""Data models for sysight.optimizer.

Defines the output structure of the optimizer (patch_plan.json).
"""

from __future__ import annotations

from dataclasses import dataclass, asdict


@dataclass
class MetricProbe:
    """Instructions for how the executor should measure the baseline/improvement."""

    run_cmd: str
    grep_pattern: str
    baseline_hint: str

    @classmethod
    def from_dict(cls, data: dict) -> MetricProbe:
        return cls(
            run_cmd=data.get("run_cmd", ""),
            grep_pattern=data.get("grep_pattern", ""),
            baseline_hint=data.get("baseline_hint", ""),
        )


@dataclass
class Patch:
    """A single proposed change for a finding."""

    id: str
    finding_id: str
    file: str
    diff: str
    rationale: str
    expected_metric: str
    summary: str = ""  # one-line human-readable description (used in commit message + CSV)

    @classmethod
    def from_dict(cls, data: dict) -> Patch:
        rationale = data.get("rationale", "")
        return cls(
            id=data.get("id", ""),
            finding_id=data.get("finding_id", ""),
            file=data.get("file", ""),
            diff=data.get("diff", ""),
            rationale=rationale,
            expected_metric=data.get("expected_metric", ""),
            # summary falls back to rationale when not explicitly provided
            summary=data.get("summary", "") or rationale,
        )


@dataclass
class PatchPlan:
    """The overall optimization plan generated by the optimizer."""

    summary: str
    metric_probe: MetricProbe
    patches: list[Patch]

    @classmethod
    def from_dict(cls, data: dict) -> PatchPlan:
        probe = data.get("metric_probe", {})
        patches_data = data.get("patches", [])
        return cls(
            summary=data.get("summary", ""),
            metric_probe=MetricProbe.from_dict(probe),
            patches=[Patch.from_dict(p) for p in patches_data],
        )

    def to_dict(self) -> dict:
        """Serialize to JSON-friendly dict."""
        return asdict(self)
