"""Optimization dataclasses. Zero internal dependencies."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Literal


def compute_span_hash(text: str) -> str:
    """Compute SHA1 hash of source code span for verification before patching."""
    return hashlib.sha1(text.encode(), usedforsecurity=False).hexdigest()[:12]


@dataclass
class PatchCandidate:
    """A proposed code change generated by the LLM.

    finding_ids can reference multiple findings when one patch fixes
    several related issues (e.g. same-file findings merged into one edit).
    old_span_hash is computed code-side after LLM returns — the LLM
    should NOT attempt to compute it.
    """
    patch_id: str
    finding_ids: list[str] = field(default_factory=list)
    file_path: str = ""
    old_span_start: int = 0
    old_span_end: int = 0
    old_span_hash: str = ""
    replacement: str = ""
    rationale: str = ""
    validation_commands: list[list[str]] = field(default_factory=list)


@dataclass
class PatchResult:
    """The result of applying and measuring a patch."""
    patch_id: str
    finding_ids: list[str] = field(default_factory=list)
    status: Literal["kept", "reverted"] = "reverted"
    reason: str = ""  # "" | "apply_failed" | "tests_failed" | "metric_regression" | "metric_unchanged"
    metric_before: float | None = None
    metric_after: float | None = None
    delta_pct: float | None = None
    lines_changed: int = 0  # number of lines in the replacement span


@dataclass
class ExecutionConfig:
    """How to run and measure the target program."""
    entry_point: str = ""
    minimal_run: list[str] = field(default_factory=list)
    metric_grep: str | None = None
    metric_lower_is_better: bool = False
    needs_instrumentation: bool = False
    test_commands: list[list[str]] = field(default_factory=list)
    build_commands: list[list[str]] = field(default_factory=list)
    env_vars: dict[str, str] = field(default_factory=dict)
    constraints: list[str] = field(default_factory=list)
    source: Literal["warmup_verified", "warmup_partial", "manual", "benchmark_case"] = "manual"
    verified_at: str = ""
